#!/usr/bin/env python3
"""Inventory the non-substantive response codes used in each wave.

Arab Barometer does not declare "don't know" and "refused" as missing values: they
are stored as ordinary high (or, in places, negative) sentinel codes, and an
unguarded mean will average them into the estimate. The codes are not consistent
across waves, so this walks the committed codebooks and writes a per-wave table of
every value label that reads as non-substantive, with the number of variables that
use it.

Writes ``docs/missing-value-codes.md``.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Substrings that mark a response as non-substantive rather than an answer.
MARKERS = (
    "don't know",
    "don’t know",
    "do not know",
    "refus",
    "declin",
    "no answer",
    "not applicable",
    "no serious answer",
    "unspecific answer",
    "missing",
)


def main() -> None:
    catalog = json.loads((ROOT / "catalog" / "catalog.json").read_text(encoding="utf-8"))
    sections = []

    for s in catalog["surveys"]:
        codebook = json.loads(
            (ROOT / s["path"] / "codebook.json").read_text(encoding="utf-8")
        )
        counts: Counter = Counter()
        for row in codebook:
            if row["value_labels"]:
                for code, label in json.loads(row["value_labels"]).items():
                    if any(m in str(label).lower() for m in MARKERS):
                        counts[(str(code), str(label))] += 1
            elif row["sentinel_codes"]:
                # A release with no value labels says nothing about what its
                # negative codes mean, so they are counted and named as sentinels
                # rather than given meanings this archive would be inventing.
                for code in json.loads(row["sentinel_codes"]):
                    counts[(str(code), "")] += 1
            elif row["observed_values"]:
                # A label-only release has no codes; the answer text is the value,
                # so it stands in the code column too.
                for label in json.loads(row["observed_values"]):
                    if any(m in str(label).lower() for m in MARKERS):
                        counts[("—", str(label))] += 1

        lines = [
            f"## {s['series_name']} {s['wave_label']}",
            "",
        ]
        if not s["has_numeric_codes"]:
            lines += [
                "Distributed as label text only, so these answers appear as the strings",
                "below rather than as codes. They are ordinary values in the data.",
                "",
            ]
        elif not s["has_value_labels"]:
            lines += [
                "The release ships codes without value labels, so what each of these means",
                "is not in the data and is not guessed here. These are the negative codes",
                "that actually occur, which in this series mark the kinds of non-answer;",
                "read the meanings off the publisher's codebook before recoding.",
                "",
            ]
        lines += [
            "| Code | Label | Variables using it |",
            "|---:|---|---:|",
        ]
        for (code, label), n in sorted(
            counts.items(), key=lambda kv: (-kv[1], kv[0][0])
        ):
            shown = label or "not labelled in the release"
            lines.append(f"| `{code}` | {shown} | {n} |")
        sections.append("\n".join(lines))

    body = "\n\n".join(sections)
    (ROOT / "docs" / "missing-value-codes.md").write_text(
        "# Non-substantive response codes\n\n"
        "Generated by `scripts/build_missing_codes.py` from the committed codebooks.\n\n"
        "None of these are declared missing in the source files, so they survive into\n"
        "every format in this repository as ordinary values. Recode them before you\n"
        "compute anything. The codes differ by wave and, within a wave, by the width of\n"
        "the variable's scale, so check the variable in `codebook.csv` rather than\n"
        "applying one rule to the whole file.\n\n"
        "The table is matched on label text, so it can catch a substantive answer that\n"
        "happens to contain one of the words -- Wave IV's \"Palestinians would refuse\" is\n"
        "an answer, not a non-response. Check the variable before recoding.\n\n" + body + "\n",
        encoding="utf-8",
    )
    print("wrote docs/missing-value-codes.md")


if __name__ == "__main__":
    main()
