#!/usr/bin/env python3
"""Index the archive by topic: which surveys asked about what, and when.

The crosswalk and the concordance both start from a variable and ask where else it
appears. This starts from a subject and asks which of the 26 surveys carry anything
on it, in which years, and which of those items recur often enough to build a series
from.

Topics and their patterns live in ``catalog/topics.json``, so what counts as an
inequality question is a file you can read and argue with rather than a judgement
buried in code. The patterns are phrase-led on purpose. A word list would take "free
and fair elections" for fairness, "overcrowded classrooms" for class and "poor
teaching" for poverty; the lexicon records those exclusions and why.

Writes ``docs/topics/<topic>.csv`` and ``docs/topics/<topic>.md``.
"""

from __future__ import annotations

import collections
import json
import re
from pathlib import Path

import pandas as pd

from extract_tunisia import ROOT

SHORT = {
    "arab-barometer": "AB",
    "arab-opinion-index": "AOI",
    "afrobarometer": "Afro",
    "world-values-survey": "WVS",
}


def survey_order() -> tuple[dict[str, dict], list[str]]:
    catalog = json.loads((ROOT / "catalog" / "catalog.json").read_text(encoding="utf-8"))
    by_key = {s["key"]: s for s in catalog["surveys"]}
    return by_key, [s["key"] for s in catalog["surveys"]]


def fieldwork_year(survey: dict) -> str:
    window = survey.get("fieldwork_tunisia")
    if window:
        years = sorted({p[:4] for p in re.findall(r"\d{4}", window)})
        return years[0] if len(years) == 1 else f"{years[0]}–{years[-1]}"
    return str(survey["fieldwork_years_series"]).replace("-", "–")


def load_variables() -> list[dict]:
    frame = pd.read_csv(ROOT / "docs" / "crosswalk.csv", keep_default_na=False)
    tags = [
        c[: -len("_text")]
        for c in frame.columns
        if c.endswith("_text") and f"{c[: -len('_text')]}_name" in frame.columns
    ]
    out = []
    for _, row in frame.iterrows():
        for tag in tags:
            if row[f"{tag}_name"] and row[f"{tag}_text"]:
                out.append(
                    {
                        "series": row["series"],
                        "survey": tag,
                        "variable": row[f"{tag}_name"],
                        "question_text": str(row[f"{tag}_text"]),
                    }
                )
    return out


def concordance_groups() -> dict[tuple[str, str], str]:
    """Which concordance group each variable belongs to, if any."""
    path = ROOT / "docs" / "question-concordance.csv"
    if not path.exists():
        return {}
    frame = pd.read_csv(path)
    return {
        (r["survey"], str(r["variable"]).upper()): r["cluster"] for _, r in frame.iterrows()
    }


def match(topic: dict, variables: list[dict], groups: dict) -> pd.DataFrame:
    compiled = {
        name: [re.compile(p, re.I) for p in facet["patterns"]]
        for name, facet in topic["facets"].items()
    }
    rows = []
    for item in variables:
        text = item["question_text"]
        hit = [name for name, patterns in compiled.items() if any(p.search(text) for p in patterns)]
        if not hit:
            continue
        rows.append(
            {
                **item,
                "facets": ";".join(sorted(hit)),
                "concordance_group": groups.get(
                    (item["survey"], item["variable"].upper()), ""
                ),
            }
        )
    return pd.DataFrame(rows)


def figure_block(topic: dict) -> list[str]:
    """Figures a topic declares in ``catalog/topics.json``.

    Rendered whether or not the files are on disk yet. Gating on existence would make
    this script depend on the figure build, which already depends on the CSV this
    script writes — so a clean rebuild would need two passes to produce one page.
    ``verify.py`` checks that every declared figure exists instead, which turns a
    missing file into an error rather than a section that quietly disappears.
    """
    declared = topic.get("figures")
    if not declared:
        return []
    lines = ["## Figures", ""]
    for figure in declared:
        link = f"../../main/figures/{figure['file']}"
        lines += [
            f"### {figure['title']}",
            "",
            f"[![{figure['title']}]({link}.png)]({link}.png)",
            "",
            figure["caption"],
            "",
            f"[PNG]({link}.png) · [SVG]({link}.svg) · rebuilt with "
            f"`python3 {figure['script']}`",
            "",
        ]
    return lines


def render(topic: dict, found: pd.DataFrame, by_key: dict, order: list[str]) -> str:
    facets = topic["facets"]
    lines = [
        f"# {topic['title']}",
        "",
        topic["description"],
        "",
        f"Generated by `scripts/build_topic_index.py` from the lexicon in",
        "[`catalog/topics.json`](../../catalog/topics.json). The full table is",
        f"[`{topic['slug']}.csv`]({topic['slug']}.csv), one row per variable.",
        "",
        f"**{len(found):,} variables across {found['survey'].nunique()} of the "
        f"{len(order)} surveys.**",
        "",
    ]
    lines += figure_block(topic)
    lines += [
        "## By facet",
        "",
        "| Facet | Variables | Surveys | Series |",
        "|---|---:|---:|---|",
    ]
    for name, facet in facets.items():
        block = found[found["facets"].str.contains(rf"(?:^|;){re.escape(name)}(?:;|$)")]
        if block.empty:
            lines.append(f"| {facet['title']} | 0 | 0 | — |")
            continue
        series = ", ".join(sorted({SHORT.get(s, s) for s in block["series"]}))
        lines.append(
            f"| {facet['title']} | {len(block):,} | {block['survey'].nunique()} | {series} |"
        )

    lines += [
        "",
        "## By survey",
        "",
        "Which surveys carry anything on this, and how much. The year is the Tunisian",
        "fieldwork where the release records it and the publisher's range where it does not.",
        "",
        "| Survey | Year | Variables |",
        "|---|---|---:|",
    ]
    counts = found["survey"].value_counts()
    for key in order:
        survey = by_key[key]
        label = f"{SHORT.get(survey['series'], survey['series'])} {survey['wave_label']}"
        lines.append(f"| {label} | {fieldwork_year(survey)} | {int(counts.get(key, 0))} |")

    repeated = (
        found[found["concordance_group"] != ""]
        .groupby("concordance_group")
        .agg(
            surveys=("survey", "nunique"),
            series=("series", "nunique"),
            question=("question_text", lambda s: max(s, key=len)),
        )
        .sort_values(["series", "surveys"], ascending=False)
    )
    repeated = repeated[repeated["surveys"] >= 2]
    across = repeated[repeated["series"] >= 2]
    tunisia_only = found[found["variable"].str.contains("TUN", case=False, na=False)]

    lines += [
        "",
        "## Asked in more than one survey",
        "",
        f"{len(repeated):,} of these questions recur, which is where a series over time",
        "could start. Groups come from [`../question-concordance.md`](../question-concordance.md);",
        "check its `scale` column before pooling, because a repeated question is not",
        "automatically a repeated measurement.",
        "",
    ]
    if across.empty:
        lines += [
            "**None of them recurs across two programmes.** Every one belongs to a single",
            "series, so a run over time can be built inside Arab Barometer, or inside the Arab",
            "Opinion Index, and not between them. There is no identical item here to",
            "triangulate on, which is the sharp version of the concordance's finding that no",
            "cross-series question shares a response scale.",
            "",
        ]
    else:
        lines += [
            f"**{len(across):,} of them recurs across more than one programme**, out of",
            f"{len(repeated):,} that recur at all — so nearly every series here has to be built",
            "inside one programme. The exceptions are worth knowing by name:",
            "",
            "| Question | Surveys | Series |",
            "|---|---:|---:|",
        ]
        for _, r in across.iterrows():
            text = r["question"][:88] + ("…" if len(r["question"]) > 88 else "")
            lines.append(f"| {text} | {r['surveys']} | {r['series']} |")
        lines += [
            "",
            "Check each against `scale` in the concordance before pooling: a question two",
            "programmes both ask is still not a measurement they both take the same way.",
            "",
        ]
    lines += [
        "| Question | Surveys | Series |",
        "|---|---:|---:|",
    ]
    for _, r in repeated.head(40).iterrows():
        text = r["question"][:90] + ("…" if len(r["question"]) > 90 else "")
        lines.append(f"| {text} | {r['surveys']} | {r['series']} |")
    if len(repeated) > 40:
        lines.append(f"| _…and {len(repeated) - 40:,} more in the CSV_ | | |")

    if not tunisia_only.empty:
        lines += [
            "",
            "## Asked only in Tunisia",
            "",
            "Country-specific items, which exist nowhere else and cannot recur:",
            "",
            "| Survey | Variable | Question |",
            "|---|---|---|",
        ]
        for _, r in tunisia_only.iterrows():
            lines.append(f"| {r['survey']} | `{r['variable']}` | {r['question_text'][:88]} |")

    lines += [
        "",
        "## What the lexicon leaves out, and why",
        "",
        "Matching is lexical, so this finds questions that say what they are about. A",
        "question that measures inequality without naming it — asking your income and your",
        "father's, say — is not here, and its absence means nothing.",
        "",
        "These words were tried and rejected as false friends:",
        "",
        "| Word | Why not |",
        "|---|---|",
    ]
    for word, why in topic.get("excluded_because_they_are_false_friends", {}).items():
        lines.append(f"| `{word}` | {why} |")
    lines += [
        "",
        "The lexicon is [`catalog/topics.json`](../../catalog/topics.json). Widen or narrow",
        "it and re-run `scripts/build_topic_index.py`; nothing else has to change.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    lexicon = json.loads((ROOT / "catalog" / "topics.json").read_text(encoding="utf-8"))
    by_key, order = survey_order()
    variables = load_variables()
    groups = concordance_groups()
    out_dir = ROOT / "docs" / "topics"
    out_dir.mkdir(parents=True, exist_ok=True)

    for slug, topic in lexicon["topics"].items():
        topic = {**topic, "slug": slug}
        found = match(topic, variables, groups)
        found = found.sort_values(["facets", "series", "survey", "variable"])
        found.to_csv(out_dir / f"{slug}.csv", index=False)
        (out_dir / f"{slug}.md").write_text(
            render(topic, found, by_key, order), encoding="utf-8"
        )
        print(f"{slug}: {len(found):,} variables in {found['survey'].nunique()} surveys")
        for name, facet in topic["facets"].items():
            block = found[found["facets"].str.contains(rf"(?:^|;){re.escape(name)}(?:;|$)")]
            print(f"   {facet['title']:<38}{len(block):>5} in {block['survey'].nunique():>2} surveys")


if __name__ == "__main__":
    main()
