#!/usr/bin/env python3
"""Inventory the non-substantive response codes used in each wave.

Arab Barometer does not declare "don't know" and "refused" as missing values: they
are stored as ordinary high (or, in places, negative) sentinel codes, and an
unguarded mean will average them into the estimate. The codes are not consistent
across waves, so this walks the committed codebooks and writes a per-wave table of
every value label that reads as non-substantive, with the number of variables that
use it.

Writes ``docs/missing-value-codes.md``.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Substrings that mark a response as non-substantive rather than an answer.
MARKERS = (
    "don't know",
    "don’t know",
    "do not know",
    "refus",
    "declin",
    "no answer",
    "not applicable",
    "no serious answer",
    "unspecific answer",
    "missing",
)


def main() -> None:
    catalog = json.loads((ROOT / "catalog" / "catalog.json").read_text(encoding="utf-8"))
    sections = []

    for s in catalog["surveys"]:
        codebook = json.loads(
            (ROOT / s["path"] / "codebook.json").read_text(encoding="utf-8")
        )
        counts: Counter = Counter()
        for row in codebook:
            if not row["value_labels"]:
                continue
            for code, label in json.loads(row["value_labels"]).items():
                if any(m in str(label).lower() for m in MARKERS):
                    counts[(str(code), str(label))] += 1

        lines = [
            f"## {s['series_name']} {s['wave_label']}",
            "",
            "| Code | Label | Variables using it |",
            "|---:|---|---:|",
        ]
        for (code, label), n in sorted(
            counts.items(), key=lambda kv: (-kv[1], kv[0][0])
        ):
            lines.append(f"| `{code}` | {label} | {n} |")
        sections.append("\n".join(lines))

    body = "\n\n".join(sections)
    (ROOT / "docs" / "missing-value-codes.md").write_text(
        "# Non-substantive response codes\n\n"
        "Generated by `scripts/build_missing_codes.py` from the committed codebooks.\n\n"
        "None of these are declared missing in the source files, so they survive into\n"
        "every format in this repository as ordinary values. Recode them before you\n"
        "compute anything. The codes differ by wave and, within a wave, by the width of\n"
        "the variable's scale, so check the variable in `codebook.csv` rather than\n"
        "applying one rule to the whole file.\n\n" + body + "\n",
        encoding="utf-8",
    )
    print("wrote docs/missing-value-codes.md")


if __name__ == "__main__":
    main()
